[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "reconciler-cli"
version = "0.1.0"
dependencies = ["typer"]

[project.scripts]
cli = "reconciler_cli.main:app"

[project.optional-dependencies]
dev = ["black==25.9.0"]