[project]
name = "reconciler-cli"
version = "0.1.0"
dependencies = ["typer"]

[project.scripts]
cli = "main:app"

[project.optional-dependencies]
dev = ["black==25.9.0"]

[tool.setuptools.packages.find]
where = ["src"]
